srmainwaring/terrain_nav_py

src/terrain_nav_py/path.py
tests/test_path.py

- Fix import
- Implement
- get_end_of_current_segment
- get_current_segment_index
- get_length
- Add test
- Add license notice

Path: implement additional methods

---

src/terrain_nav_py/dubins_path.py
tests/test_dubins_path.py

- Port DubinsPath class to Python and add tests.
- Add tests and fix issues.
- Add license notice.

dubins_path: implement DubinsPath data class and tests

---

src/terrain_nav_py/dubins_path.py

- Remove unused module `planner`.
- Add type annotations to `DubinsPath` member variables.

dubins_path: add type annotation to member variables

---

src/terrain_nav_py/dubins_airplane.py
tests/test_dubins_airplane.py

Outline DubinsAirplaneStateSpace subclassing from py-ompl objects.
- Add nested classes to facilitate state access.
- Add test case outline.

dubins_airplane: initial port of DubinsAirplaneStateSpace using py-ompl

---

src/terrain_nav_py/dubins_airplane.py
tests/test_dubins_airplane.py

Port `DubinsAirplaneStateSpace` methods to Python.
- Testing is incomplete, but all methods are ported and module imports correctly.

dubins_airplane: implement DubinsAirplaneStateSpace methods

---

src/terrain_nav_py/terrain_ompl.py
tests/test_terrain_ompl.py

- Implement an ompl state validity checker and state sampler for terrain.
- Add a mock grid map for testing.

terrain_ompl: implement terrain validity checker and sampler

---

src/terrain_nav_py/terrain_ompl_rrt.py
tests/test_terrain_ompl_rrt.py

Port `TerrainOmplRrt` from C++ to Python.
Testing is incomplete, but all methods are ported and module imports correctly.

terrain_ompl_rrt: implement terrain ompl rrt planner

---

src/terrain_nav_py/dubins_airplane.py
src/terrain_nav_py/dubins_path.py
src/terrain_nav_py/path_segment.py
src/terrain_nav_py/terrain_ompl.py
src/terrain_nav_py/terrain_ompl_rrt.py
tests/test_dubins_airplane.py
tests/test_terrain_ompl_rrt.py

Fix various issues so that the planner is in working order.

terrain_ompl_rrt: get basic test running

---

src/terrain_nav_py/grid_map.py
src/terrain_nav_py/terrain_map.py
tests/test_grid_map.py
tests/test_terrain_ompl_rrt.py

Integrate SRTM1 terrain data using the elevation module from MAVProxy.
There are outstanding issues with the planner, but the terrain may now be plotted and the planner states visualised.

Integrate SRTM1 terrain data

---

src/terrain_nav_py/dubins_airplane.py
src/terrain_nav_py/dubins_path.py
src/terrain_nav_py/terrain_ompl_rrt.py
tests/test_terrain_ompl_rrt.py

Update docstrings and remove comments discussing use of the ompl bindings versus the native C++ code.
- Fully document `dubins_path`.

Update comments and docstrings

---

src/terrain_nav_py/grid_map.py
tests/test_terrain_ompl_rrt.py

Use the ENU convention for the world frame. This is consistent with ROS.
- Add settors to `GridMap` for grid length and grid spacing.
- Use the `GridMap` to set the plot limits.

Use ENU convention for world frame

---

src/terrain_nav_py/dubins_airplane.py
src/terrain_nav_py/terrain_ompl_rrt.py
tests/test_terrain_ompl_rrt.py

Add velocity vectors to the paths in the terrain plots.

Add velocity to terrain path plots

---

tests/test_grid_map.py

grid_map: update test to ENU coordinates

---

src/terrain_nav_py/dubins_airplane.py
src/terrain_nav_py/dubins_path.py
src/terrain_nav_py/ompl_setup.py
src/terrain_nav_py/path.py
src/terrain_nav_py/path_segment.py
src/terrain_nav_py/terrain_ompl.py
src/terrain_nav_py/terrain_ompl_rrt.py
src/terrain_nav_py/util.py
tests/test_path.py
tests/test_path_segment.py
tests/test_terrain_ompl_rrt.py
tests/test_util.py

Fixes https://github.com/srmainwaring/terrain_nav_py/issues/16
Various fixes and improvements that result in a working planner. Generated paths are consistent with the original C++ version. 
_Figure 1: correctly generated path including spiral_
_Figure 2: planned path around Boulder, Colorado_

Fix generation of trajectory from solution state vector

---

.github/workflows/ubuntu-build.yml

* Make this workflow closer to working on Ubuntu 22
* And break up install/test

Use python3-venv as the package

---

.github/workflows/ubuntu-build.yml
src/terrain_nav_py/path.py

Add a build for Ubuntu 22.04 using Python 3.10
- Add job to workflow.
- Update `path.py` to use an alternative to `typing.Self` on Python versions < 3.11

Add Ubuntu 22.04 build to CI

---

src/terrain_nav_py/terrain_ompl_rrt.py

Resolve a div by zero error when the start and end states are  the same resulting in a zero length segment.

Handle zero length segment in path interpolation

---

src/terrain_nav_py/dubins_airplane.py
src/terrain_nav_py/terrain_ompl.py
tests/test_dubins_airplane.py

Add accessors that return the Dubins state position and yaw in a single call.

Add Dubins Airplane state accessors

---

tests/test_terrain_ompl_rrt.py

This location stress tests the `distance-surface` calculation used to determine if a sampled state is valid.
- The change in #31 partially addresses ensuring the generated path is always above the `min_altitude` limit.
- A full solution requires correct implementation of the distance transform in the terrain map C++ code.

Update test case using Davos steep terrain example

---

.github/workflows/ubuntu-build.yml
src/terrain_nav_py/grid_map.py
tests/test_grid_map.py

Add calculation of the distance surface layer to GridMap.

Add distance surface calculation

---

src/terrain_nav_py/dubins_airplane.py
src/terrain_nav_py/terrain_ompl_rrt.py
tests/test_terrain_ompl_rrt.py

Prefer `np.linspace` to `np.arange` when creating samples and interpolating.

Use numpy linspace rather than arange

---

.github/workflows/ubuntu-build.yml
pyproject.toml

Add Python dependencies to `pyproject.toml` and handle different Python, platform and machine dependencies.
- Update  `pyproject.toml` with all dependencies.
- Update GitHub workflow ubuntu-build to use project for the Python install.

Update pyproject.toml dependencies

---

src/terrain_nav_py/terrain_ompl_rrt.py
tests/test_dubins_airplane.py
tests/test_terrain_ompl_rrt.py

Check that point is inside map bounds in `validatePosition`.

Ensure position validator checks point inside map extents

---

src/terrain_nav_py/ompl_setup.py
src/terrain_nav_py/terrain_ompl.py

Add checks for exclusion circles, inclusion polygons and inclusion circles.

Add remaining polyfence types

---

pyproject.toml

Causing conflicts with MAVProxy on Ubuntu.

Remove version requirements on packages

---

src/terrain_nav_py/terrain_planner.py

Use `@dataclass` for message and command classes passed between processes.

Use dataclasses for planner messages
